name: cht_ema_surveys
description: "Provides pre-built surveys for use in ecological momentary assessment (EMA) studies."
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev
homepage:

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  research_package:
    git:
      url: https://github.com/mario-bermonti/research.package.git
      ref: 90829448e20fa72ce34ee740dac25849078cb2de

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  assets:
    - assets/lang/
    - lib/src/core/l10n/
