name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/dependencies
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.19.0
        with:
          channel: stable
          flutter-version: 3.19.4
          cache: true

      - name: Install package dependencies
        run: flutter pub get

      - name: Install application dependencies
        working-directory: example
        run: flutter pub get

      - name: Build android apk (debug)
        working-directory: example
        run: flutter build apk --debug

  build_ios:
    runs-on: macos-14
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/dependencies
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.19.0
        with:
          channel: stable
          flutter-version: 3.19.4
          cache: true

      - name: Install package dependencies
        run: flutter pub get

      - name: Install application dependencies
        working-directory: example
        run: flutter pub get

      - name: Build iOS (no codesign)
        working-directory: example
        run: flutter build ios --no-codesign
