name: Release Drafter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, edited, reopened, synchronize, labeled, unlabeled]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: release-drafter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update the next release
        uses: release-drafter/release-drafter@v6
        with:
          # ensures our autolabel rules in release-drafter.yml work
          disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
